[package]
description = "Generic rpc framework for rust"
documentation = "https://docs.rs/librpc"
edition = "2021"
license = "MIT"
name = "librpc"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
